/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ScrollPaneLayout;

/**
 *
 * @author cesar
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form VentanaPrincipal
     */
    public ArrayList<JButton> btnImagenes;
    
    public VentanaPrincipal() {
        btnImagenes = new ArrayList<JButton>();
        
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        labTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        imgPanel = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscar.setBackground(new java.awt.Color(72, 191, 139));
        btnBuscar.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(7, 39, 29));
        btnBuscar.setText("Buscar directorio");
        btnBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        labTitulo.setFont(new java.awt.Font("Nirmala UI", 3, 27)); // NOI18N
        labTitulo.setForeground(new java.awt.Color(15, 69, 51));
        labTitulo.setText("Directorio de imagenes");

        jScrollPane2.setBackground(new java.awt.Color(230, 230, 230));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        imgPanel.setBackground(new java.awt.Color(230, 230, 230));
        imgPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));
        jScrollPane2.setViewportView(imgPanel);

        btnSalir.setBackground(new java.awt.Color(72, 191, 139));
        btnSalir.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(7, 39, 29));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void agregarImagen(String ruta){
        int tamaño = 180;
           
        ImageIcon imagen = new ImageIcon(getClass().getResource(ruta));
        Image imagenEscalada = imagen.getImage().getScaledInstance(tamaño, tamaño, Image.SCALE_SMOOTH);
        imagen = new ImageIcon(imagenEscalada);
        JButton imageButton= new JButton(imagen);
        
        imageButton.setActionCommand("BotonImg"+btnImagenes.size());
        btnImagenes.add(imageButton);
        //imageButton.setActionCommand("BotonImg"+btnImagenes.size()); // Empieza en 1??
        
        imgPanel.add(imageButton);
    }
    
    public void mensajeConsola(String m){
        System.out.println(m);
    }
    
    public void ventanaEmergente(String m){
        JOptionPane.showMessageDialog(null, m);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnSalir;
    public javax.swing.JPanel imgPanel;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel labTitulo;
    // End of variables declaration//GEN-END:variables
}
